version: "3.4"

# Development environment override
services:
  php:
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      # If you develop on Mac or Windows you can remove the var/ and vendor/ directories 
      #  from the bind-mount for better performance by enabling the next 2 lines
      # - /srv/app/var
      # - /srv/app/vendor
    environment:
      APP_ENV: dev

  caddy:
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/app/public:ro

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
