version: "3.4"

services:
  php:
    build:
      context: .
      target: symfony_php
      args:
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        STABILITY: ${STABILITY:-stable}
        SERVER_NAME: ${SERVER_NAME:-localhost}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      SYMFONY_VERSION:

  nginx:
    build:
      context: .
      target: symfony_nginx
    depends_on:
      - php
    ports:
      - "80:80"
