on:
  schedule:
    - cron:  "0 0 * * */1"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/dunglas/symfony-docker"
          source_branch: "main"
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "Sync with Upstream"
          pr_body: " *Automated PR*"
          pr_assignee: "Pietrucci-Blacher"
          pr_label: "auto-pr"
